import logging

from starlette.datastructures import Headers
from starlette.responses import Response
from starlette.types import ASGIApp, Receive, Scope, Send

logger = logging.getLogger(__name__)


class QueuePathRewriterMiddleware:
    """
    Rewrites a specified part of the request path.

    Parameters
    ----------
    app : ASGIApp
        Application instance the middleware is being registered to.
    """

    def __init__(self, app: ASGIApp) -> None:
        """
        Initializes the QueuePathRewriterMiddleware.
        """
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> Response:
        """
        Rewrites a specified part of the request path.

        Parameters
        ----------
        request : Request
            The incoming request.
        scope : Scope
            The ASGI scope.
        receive : Receive
            The receive channel.

        Returns
        -------
        Response
            The response generated by the middleware.
        """
        if scope["type"] != "http" or scope["method"] != "POST":
            return await self.app(scope, receive, send)

        logger.debug(f"Received scope: {scope}")

        header = Headers(scope=scope)

        queue = header["endpoint"]

        if "/" in queue:
            queue = queue.rsplit("/")[-1]

        scope["path"] = "/" + queue

        await self.app(scope, receive, send)
